// Command gen-docs writes the public type reference under docs/reference from
// the embedded catalog and gen/warnings.txt.
//
// The pages are COMMITTED, and cmd/gen-docs is the only thing allowed to write
// them. A page hand-edited to say something the catalog does not say is worse
// than no page: the catalog is what the plugin actually serves. main_test.go
// fails when what is committed differs from what this command would write, so a
// regeneration nobody committed is a red build rather than a quiet drift.
//
// Everything here sorts before it iterates. A docs generator that reorders its
// own output between runs makes every regeneration an unreviewable diff, and
// Go's map iteration order is deliberately random, so "it looked stable" is not
// evidence. TestRenderingIsDeterministic re-renders and compares.
package main

import (
	"bufio"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/infrena/infrena-provider-gcp/internal/catalog"
)

func main() {
	out := flag.String("out", "docs/reference", "directory to write the reference into")
	warnPath := flag.String("warnings", "gen/warnings.txt", "the generator's warnings file")
	check := flag.Bool("check", false, "do not write; exit non-zero if what is on disk differs")
	flag.Parse()

	c, err := catalog.Load()
	if err != nil {
		log.Fatalf("gen-docs: load catalog: %v", err)
	}
	raw, err := os.ReadFile(*warnPath)
	if err != nil {
		log.Fatalf("gen-docs: %v", err)
	}
	ws, err := parseWarnings(string(raw))
	if err != nil {
		log.Fatalf("gen-docs: %s: %v", *warnPath, err)
	}

	pages := Pages(c, ws)
	if *check {
		diff, err := compare(*out, pages)
		if err != nil {
			log.Fatalf("gen-docs: %v", err)
		}
		if len(diff) > 0 {
			for _, d := range diff {
				fmt.Fprintln(os.Stderr, d)
			}
			log.Fatalf("gen-docs: %d page(s) out of date; run `go run ./cmd/gen-docs`", len(diff))
		}
		fmt.Printf("gen-docs: %d pages up to date\n", len(pages))
		return
	}
	if err := write(*out, pages); err != nil {
		log.Fatalf("gen-docs: %v", err)
	}
	fmt.Printf("gen-docs: wrote %d pages for %d types\n", len(pages), len(c.Types))
}

// ---------------------------------------------------------------------------
// warnings
// ---------------------------------------------------------------------------

// warning is one row of gen/warnings.txt. The file is tab-separated and has
// two shapes: three fields for a type that did not ship (tier, product/Resource,
// reason) and four for one that ships without create (nocreate, type, create
// template, missing placeholders).
type warning struct {
	Tier     string
	Subject  string
	Template string
	Reason   string
}

// parseWarnings reads the file. It REFUSES a row it does not understand rather
// than skipping it, because the whole point of not-shipped.md is that nothing
// disappears quietly between the generator and the reader.
func parseWarnings(text string) ([]warning, error) {
	var ws []warning
	sc := bufio.NewScanner(strings.NewReader(text))
	for line := 1; sc.Scan(); line++ {
		s := sc.Text()
		if strings.TrimSpace(s) == "" || strings.HasPrefix(s, "#") {
			continue
		}
		f := strings.Split(s, "\t")
		switch len(f) {
		case 3:
			ws = append(ws, warning{Tier: f[0], Subject: f[1], Reason: f[2]})
		case 4:
			ws = append(ws, warning{Tier: f[0], Subject: f[1], Template: f[2], Reason: f[3]})
		default:
			return nil, fmt.Errorf("line %d: %d tab-separated fields, want 3 or 4: %q", line, len(f), s)
		}
	}
	return ws, sc.Err()
}

// category collapses a reason to the group it belongs in. The detail after a
// ":" or ";" is the part that differs per type (which hooks, which method), and
// it stays on the row; the part in front is what the grouping is for.
func category(reason string) string {
	if i := strings.IndexAny(reason, ":;"); i >= 0 {
		return strings.TrimSpace(reason[:i])
	}
	if strings.HasPrefix(reason, "legacy alias of ") {
		return "legacy alias of a type that does ship"
	}
	return reason
}

// detail is the per-row remainder: what category left behind.
func detail(reason string) string {
	if i := strings.IndexAny(reason, ":;"); i >= 0 {
		return strings.TrimSpace(reason[i+1:])
	}
	if strings.HasPrefix(reason, "legacy alias of ") {
		return strings.TrimPrefix(reason, "legacy alias of ")
	}
	return ""
}

// ---------------------------------------------------------------------------
// rendering
// ---------------------------------------------------------------------------

const banner = "<!-- GENERATED by cmd/gen-docs from the embedded catalog. Do not edit by hand. -->"

// Pages renders the whole reference. Keys are slash-separated paths relative to
// the output root.
func Pages(c *catalog.Catalog, ws []warning) map[string]string {
	byService := map[string][]*catalog.Type{}
	for _, t := range c.Types {
		byService[t.Service] = append(byService[t.Service], t)
	}
	services := make([]string, 0, len(byService))
	for s, ts := range byService {
		services = append(services, s)
		sort.Slice(ts, func(i, j int) bool { return ts[i].Name < ts[j].Name })
	}
	sort.Strings(services)

	pages := map[string]string{
		"README.md":      renderIndex(c, services, byService, ws),
		"not-shipped.md": renderNotShipped(ws),
	}
	for _, s := range services {
		pages[s+"/README.md"] = renderService(s, byService[s])
		for _, t := range byService[s] {
			pages[s+"/"+t.Name+".md"] = renderType(t)
		}
	}
	return pages
}

func renderIndex(c *catalog.Catalog, services []string, byService map[string][]*catalog.Type, ws []warning) string {
	var b strings.Builder
	p := func(f string, a ...any) { fmt.Fprintf(&b, f, a...) }

	p("%s\n\n# GCP type reference\n\n", banner)
	p("This plugin serves **%d types** across %d Google Cloud services. ", len(c.Types), len(services))
	p("Every page below is generated from the catalog the plugin itself loads, so it says what the plugin does, not what it intends to do.\n\n")
	p("- Catalog generated: %s\n", c.Generated)
	p("- From magic-modules commit: `%s`\n\n", c.MMV1Commit)
	p("**[Types that are not served, and why](not-shipped.md)** — %d entries. ", countNotShipped(ws))
	p("Read that page first if the type you want is missing from this one.\n\n")

	p("## Services\n\n")
	p("| Service | Types |\n| --- | --- |\n")
	for _, s := range services {
		p("| [%s](%s/README.md) | %d |\n", s, s, len(byService[s]))
	}

	p("\n## How to read a type page\n\n")
	p("- **What it can do** is derived from the catalog the same way `infrena explain` derives it. ")
	p("A type whose create url has a placeholder nothing can fill reports `create: no`, and the page names the placeholder.\n")
	p("- **Attributes** lists every attribute at every depth. A `.` is a field of an object; a `[]` is the element of a list. ")
	p("Both are real nesting edges in the catalog and both are followed here.\n")
	p("- **Also spelled** lists the alternative spellings configuration accepts for an attribute, ")
	p("including the snake_case alias emitted for every camelCase name.\n")
	p("- **Set by** is `required` (you must write it), `optional` (you may) or `output only` (GCP chooses it; configuration may not set it).\n")
	p("- A note of `same fields as x.y` means the attribute's subtree is identical to one already listed on the page. ")
	p("Several GCP schemas are recursive, and expanding them twice would repeat thousands of identical rows.\n")
	return b.String()
}

func countNotShipped(ws []warning) int {
	n := 0
	for _, w := range ws {
		if w.Tier != "nocreate" {
			n++
		}
	}
	return n
}

func renderService(service string, ts []*catalog.Type) string {
	var b strings.Builder
	p := func(f string, a ...any) { fmt.Fprintf(&b, f, a...) }

	p("%s\n\n# %s\n\n", banner, service)
	p("%d type(s). [Back to the index](../README.md).\n\n", len(ts))
	p("| Type | Create | Update | Import | What it is |\n| --- | --- | --- | --- | --- |\n")
	for _, t := range ts {
		p("| [`%s`](%s.md) | %s | %s | %s | %s |\n",
			t.Name, t.Name,
			yesNo(canCreate(t)), yesNo(t.UpdateVerb != ""), yesNo(t.ImportFormat != ""),
			cell(firstSentence(t.Description), 140))
	}
	return b.String()
}

func renderType(t *catalog.Type) string {
	var b strings.Builder
	p := func(f string, a ...any) { fmt.Fprintf(&b, f, a...) }

	p("%s\n\n# `%s`\n\n", banner, t.Name)
	if d := flatten(t.Description); d != "" {
		p("%s\n\n", d)
	}
	p("[%s](README.md) · [all services](../README.md)\n\n", t.Service)

	p("| | |\n| --- | --- |\n")
	p("| Service | %s |\n", t.Service)
	p("| Scope | %s |\n", scopeName(t.Scope))
	if t.AssetType != "" {
		p("| Asset type | `%s` |\n", t.AssetType)
	}
	if t.ParentRoot != "" {
		p("| Hangs off | `%s` |\n", t.ParentRoot)
	}
	p("| Tier | %d%s |\n", t.Tier, paren(t.TierReason))
	p("| Mutation timeout | %ds |\n", t.TimeoutSeconds)

	p("\n## What it can do\n\n")
	p("| Operation | Supported | How |\n| --- | --- | --- |\n")
	missing := t.UnresolvedCreatePlaceholders()
	createHow := "`POST " + code(t.CreateTemplate()) + "`"
	if len(missing) > 0 {
		createHow = "the create url `" + code(t.CreateTemplate()) + "` needs " +
			list(missing) + ", which nothing supplies: no provider setting (project, region, zone, location), " +
			"no stored binding, and no settable attribute of this type"
	}
	p("| Create | %s | %s |\n", yesNo(len(missing) == 0), createHow)
	readHow := "`GET " + code(orElse(t.SelfLink, t.BaseURL)) + "`"
	if t.ReadVia != "" {
		readHow = "by `" + t.ReadVia + "`: " + readHow
	}
	p("| Read | yes | %s |\n", readHow)
	updateHow := ""
	if t.UpdateVerb != "" {
		updateHow = "`" + t.UpdateVerb + " " + code(orElse(t.UpdateURL, orElse(t.SelfLink, t.BaseURL))) + "`"
		if t.UpdateVerb == "PUT" {
			updateHow += ", the whole resource: read first, with the change written in"
		}
		if t.UpdateMask {
			updateHow += ", with an update mask naming the changed fields"
		}
	} else {
		updateHow = "publishes no update method; every change to it replaces the resource"
	}
	p("| Update | %s | %s |\n", yesNo(t.UpdateVerb != ""), updateHow)
	p("| Delete | yes | `DELETE %s` |\n", code(orElse(t.DeleteURL, orElse(t.SelfLink, t.BaseURL))))
	importHow := "no import id shape is published for this type"
	if t.ImportFormat != "" {
		importHow = "by id, see below"
	}
	p("| Import | %s | %s |\n", yesNo(t.ImportFormat != ""), importHow)

	p("\n## Import id\n\n")
	if t.ImportFormat == "" {
		p("This type cannot be imported: magic-modules publishes no id shape for it.\n")
	} else {
		forms := strings.Split(t.ImportFormat, "\n")
		if len(forms) == 1 {
			p("```\n%s\n```\n", strings.TrimSpace(forms[0]))
		} else {
			p("Any one of these shapes is accepted, tried in order:\n\n```\n")
			for _, f := range forms {
				if f = strings.TrimSpace(f); f != "" {
					p("%s\n", f)
				}
			}
			p("```\n")
		}
	}

	p("\n## Attributes\n\n")
	rows := attrRows(t)
	p("%d attribute(s), at every depth. A `.` is a field of an object; `[]` is the element of a list.\n\n", len(rows))
	p("| Attribute | Also spelled | Type | Set by | Notes | Description |\n")
	p("| --- | --- | --- | --- | --- | --- |\n")
	for _, r := range rows {
		p("| `%s` | %s | %s | %s | %s | %s |\n",
			r.Path, r.spellings(), "`"+r.Attr.Kind.String()+"`", setBy(r.Attr), r.notes(), cell(flatten(r.Attr.Description), 200))
	}

	if refs := refRows(rows); len(refs) > 0 {
		p("\n## References\n\n")
		p("These attributes name another type. infrena uses them to order a plan.\n\n")
		p("| Attribute | Points at |\n| --- | --- |\n")
		for _, r := range refs {
			p("| `%s` | `%s.%s` |\n", r.Path, r.Attr.Ref.Type, r.Attr.Ref.Attribute)
		}
	}
	return b.String()
}

func renderNotShipped(ws []warning) string {
	var b strings.Builder
	p := func(f string, a ...any) { fmt.Fprintf(&b, f, a...) }

	p("%s\n\n# Types this plugin does not serve\n\n", banner)
	p("If a GCP resource is not in the [reference](README.md), it is on this page with the reason. ")
	p("There is no third list.\n\n")
	p("Every candidate type is sorted into a tier before anything is generated:\n\n")
	p("- **tier 1** ships as it stands.\n")
	p("- **tier 2** has provider-side wire hooks — custom import, an encoder, a pre-update step — that change what goes on the wire. ")
	p("A tier-2 type ships only once somebody writes a ruling in `gen/overlay.yaml` that names **every** hook on it and says what each one does. ")
	p("Naming most of them is not enough: an unnamed hook is behaviour this plugin would silently not perform.\n")
	p("- **tier 3** is not representable at all — no create method, no delete method, beta-only, or excluded upstream.\n\n")
	p("So a type listed under \"unruled wire hooks\" below is not impossible. It is unwritten. ")
	p("The hooks named on its row are exactly what a ruling has to account for.\n\n")

	var shipped, notShipped []warning
	for _, w := range ws {
		if w.Tier == "nocreate" {
			shipped = append(shipped, w)
			continue
		}
		notShipped = append(notShipped, w)
	}

	groups := map[string][]warning{}
	for _, w := range notShipped {
		groups[category(w.Reason)] = append(groups[category(w.Reason)], w)
	}
	names := make([]string, 0, len(groups))
	for n := range groups {
		names = append(names, n)
	}
	sort.Slice(names, func(i, j int) bool {
		if len(groups[names[i]]) != len(groups[names[j]]) {
			return len(groups[names[i]]) > len(groups[names[j]])
		}
		return names[i] < names[j]
	})

	p("## Summary\n\n| Reason | Types |\n| --- | --- |\n")
	for _, n := range names {
		p("| [%s](#%s) | %d |\n", n, anchor(n), len(groups[n]))
	}
	p("| [shipped, but cannot be created](#shipped-but-cannot-be-created) | %d |\n", len(shipped))
	p("\n**%d** types did not ship. **%d** more ship without a create.\n", len(notShipped), len(shipped))

	for _, n := range names {
		g := groups[n]
		sort.Slice(g, func(i, j int) bool { return g[i].Subject < g[j].Subject })
		p("\n## %s\n\n", n)
		p("%s\n\n", explain(n))
		p("| Type | Tier | Detail |\n| --- | --- | --- |\n")
		for _, w := range g {
			p("| `%s` | %s | %s |\n", w.Subject, strings.TrimPrefix(w.Tier, "tier"), cell(detail(w.Reason), 200))
		}
	}

	if len(shipped) > 0 {
		sort.Slice(shipped, func(i, j int) bool { return shipped[i].Subject < shipped[j].Subject })
		p("\n## Shipped, but cannot be created\n\n")
		p("These types **are** in the reference. They read, import, discover and delete. ")
		p("What they cannot do is create, because their create url has a placeholder nothing supplies — ")
		p("not an instance setting (project, region, zone, location), not a stored binding, and not a settable attribute of their own. ")
		p("The create is refused before a request is sent, rather than by Google answering a url with an empty segment in it.\n\n")
		p("| Type | Create url | Needs |\n| --- | --- | --- |\n")
		for _, w := range shipped {
			p("| `%s` | `%s` | %s |\n", w.Subject, code(w.Template), cell(strings.TrimPrefix(w.Reason, "needs "), 120))
		}
	}
	return b.String()
}

// explain gives each group the sentence a reader needs to know what to do next.
// An unrecognised category still gets a row in the table; it just gets no extra
// sentence, so a new reason from the generator shows up rather than vanishing.
func explain(category string) string {
	switch category {
	case "unruled wire hooks":
		return "The upstream definition carries hooks that rewrite the request or response. " +
			"Each of these ships as soon as a ruling in `gen/overlay.yaml` names every hook on the row and says what it does."
	case "no insert or create method":
		return "The API publishes no way to create one. Most of these are read-only collections — locations, operations, supported flags — " +
			"that exist to be listed, not managed."
	case "no delete method":
		return "The API publishes no way to delete one. A type infrena cannot remove is a type it cannot honestly manage."
	case "magic-modules marks it exclude":
		return "Upstream excludes the resource from generation, so there is no definition to work from."
	case "min_version is beta, not ga":
		return "Only a beta API serves it. This plugin generates from GA surfaces."
	case "legacy alias of a type that does ship":
		return "An older url for a resource another type already serves, under the name in the Detail column. Use that type."
	case "no get method":
		return "The API publishes no get. Reading one means listing its parent, which needs a ruling with `read_via` in `gen/overlay.yaml`."
	}
	return "Reported by the generator."
}

// ---------------------------------------------------------------------------
// attributes
// ---------------------------------------------------------------------------

// attrRow is one attribute at one path.
type attrRow struct {
	Path string
	Attr *catalog.Attr
	// SameAs is the earlier path whose subtree is identical to this one's.
	// Several GCP schemas are recursive -- bigquery's standard SQL data type
	// nests into itself six deep -- and expanding each occurrence in full
	// turns one type's page into 3708 rows, most of them the same rows again.
	// The attribute is still listed; only the repeat of its subtree is not.
	SameAs string
}

// attrRows walks a type's whole attribute tree, depth first, in sorted order.
//
// It follows BOTH nesting edges. Fields is an object's attributes and Elem is a
// list's element, and they are not alternatives: measured on this catalog
// (2026-09-23), a walk that follows only Fields reaches 8017 of the 19730
// attribute paths -- it drops 59% of them, every one inside a repeated block.
// Anything that only knew about Fields would be silently, confidently wrong
// about the whole of GCP's list-of-object shape.
func attrRows(t *catalog.Type) []attrRow {
	var out []attrRow
	seen := map[string]string{}
	var walk func(path string, a *catalog.Attr)
	walk = func(path string, a *catalog.Attr) {
		row := attrRow{Path: path, Attr: a}
		if len(a.Fields) > 0 || a.Elem != nil {
			k := shape(a)
			if prev, ok := seen[k]; ok {
				row.SameAs = prev
				out = append(out, row)
				return
			}
			seen[k] = path
		}
		out = append(out, row)
		for _, n := range sortedKeys(a.Fields) {
			walk(path+"."+n, a.Fields[n])
		}
		if a.Elem != nil {
			walk(path+"[]", a.Elem)
		}
	}
	for _, n := range sortedKeys(t.Attributes) {
		walk(n, t.Attributes[n])
	}
	return out
}

// shape keys an attribute's whole subtree by content. encoding/json sorts map
// keys, so the same subtree hashes the same however it was built.
func shape(a *catalog.Attr) string {
	blob, err := json.Marshal(a)
	if err != nil {
		// An Attr is plain data with no channels, funcs or NaNs in it, so
		// this cannot happen; a unique key keeps the walk correct if it ever
		// does, rather than collapsing two different subtrees into one.
		return fmt.Sprintf("unmarshalable:%p", a)
	}
	sum := sha256.Sum256(blob)
	return hex.EncodeToString(sum[:])
}

func sortedKeys(m map[string]*catalog.Attr) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// spellings is every name configuration accepts for the attribute, plus the
// wire name when it differs from the schema name (307 attributes in this
// catalog, e.g. the schema's `type_value` for the wire's `type`).
func (r attrRow) spellings() string {
	if strings.HasSuffix(r.Path, "[]") {
		// A list element has no name of its own; it carries its list's.
		return "—"
	}
	key := r.Path
	if i := strings.LastIndexAny(key, "."); i >= 0 {
		key = key[i+1:]
	}
	var parts []string
	for _, a := range r.Attr.Aliases {
		if a != key {
			parts = append(parts, "`"+a+"`")
		}
	}
	if c := r.Attr.Canonical; c != "" && c != key {
		parts = append(parts, "wire `"+c+"`")
	}
	if len(parts) == 0 {
		return "—"
	}
	return strings.Join(parts, ", ")
}

func (r attrRow) notes() string {
	var n []string
	if r.Attr.ForceNew {
		n = append(n, "force new")
	}
	if r.Attr.CreateOnly {
		n = append(n, "create only")
	}
	if r.Attr.Sensitive {
		n = append(n, "sensitive")
	}
	if r.Attr.Opaque {
		n = append(n, "opaque")
	}
	if r.Attr.Unordered {
		n = append(n, "unordered")
	}
	if r.Attr.Ref != nil {
		n = append(n, fmt.Sprintf("refers to `%s.%s`", r.Attr.Ref.Type, r.Attr.Ref.Attribute))
	}
	if r.SameAs != "" {
		n = append(n, fmt.Sprintf("same fields as `%s`", r.SameAs))
	}
	if len(n) == 0 {
		return "—"
	}
	return strings.Join(n, ", ")
}

func refRows(rows []attrRow) []attrRow {
	var out []attrRow
	for _, r := range rows {
		if r.Attr.Ref != nil {
			out = append(out, r)
		}
	}
	return out
}

func setBy(a *catalog.Attr) string {
	switch {
	case a.Output:
		return "output only"
	case a.Required:
		return "required"
	default:
		return "optional"
	}
}

// canCreate asks the same question catalog.Definitions asks when it tells the
// host what a type can do. One rule, two readers.
func canCreate(t *catalog.Type) bool { return len(t.UnresolvedCreatePlaceholders()) == 0 }

// ---------------------------------------------------------------------------
// text
// ---------------------------------------------------------------------------

func scopeName(s catalog.Scope) string {
	switch s {
	case catalog.ScopeRegional:
		return "regional"
	case catalog.ScopeZonal:
		return "zonal"
	default:
		return "global"
	}
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "**no**"
}

func orElse(s, fallback string) string {
	if s != "" {
		return s
	}
	return fallback
}

func paren(s string) string {
	if s == "" {
		return ""
	}
	return " (" + s + ")"
}

func list(ss []string) string {
	q := make([]string, len(ss))
	for i, s := range ss {
		q[i] = "`" + s + "`"
	}
	return strings.Join(q, ", ")
}

// flatten turns a multi-line upstream description into one line a table cell
// can hold, with the characters that would be read as markup escaped.
//
// Brackets are escaped too, which looks fussy until you read what is actually
// in these descriptions: url templates carrying "[a-z0-9-]{0,61}[a-z0-9]" and
// prose carrying "[the Airflow web interface](/composer/docs/...)". Left alone,
// the first renders as an empty link and the second as a link relative to
// whatever is hosting this page -- a 404 that looks like the plugin's fault.
// A description is data. Nothing in it is markup.
func flatten(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	r := strings.NewReplacer(
		"|", "\\|",
		"<", "&lt;",
		"[", "\\[",
		"]", "\\]",
	)
	return r.Replace(s)
}

// code escapes a template for a code span. A `|` inside one still ends a table
// cell, backticks and all.
func code(s string) string { return strings.ReplaceAll(s, "|", "\\|") }

// cell truncates at a word boundary. Upstream descriptions run to paragraphs,
// and a table whose rows are paragraphs is a table nobody reads.
func cell(s string, max int) string {
	if s == "" {
		return "—"
	}
	if len(s) <= max {
		return s
	}
	cut := s[:max]
	if i := strings.LastIndex(cut, " "); i > max/2 {
		cut = cut[:i]
	}
	return strings.TrimRight(cut, " .,;:") + " …"
}

func firstSentence(s string) string {
	s = flatten(s)
	if i := strings.Index(s, ". "); i >= 0 {
		return s[:i+1]
	}
	return s
}

// anchor is GitHub's heading slug, for the summary table's links.
func anchor(heading string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(heading) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '_':
			// GitHub's slugger drops punctuation but KEEPS an underscore, so
			// "min_version is beta" anchors at "min_version-is-beta". Folding
			// it to a hyphen here would produce links that scroll nowhere.
			b.WriteRune('_')
		case r == ' ' || r == '-':
			b.WriteRune('-')
		}
	}
	return b.String()
}

// ---------------------------------------------------------------------------
// disk
// ---------------------------------------------------------------------------

// write puts every page on disk and removes any .md under the root that this
// run did not produce. A page for a type that no longer exists is a page that
// lies, and leaving it behind is how a reference outlives its catalog.
func write(root string, pages map[string]string) error {
	for _, rel := range sortedPages(pages) {
		path := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(pages[rel]), 0o644); err != nil {
			return err
		}
	}
	return prune(root, pages)
}

func prune(root string, pages map[string]string) error {
	return filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".md") {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		if _, ok := pages[filepath.ToSlash(rel)]; !ok {
			return os.Remove(path)
		}
		return nil
	})
}

// compare reports every page that is missing, stale or left over. It returns
// the differences rather than the first one, because "regenerate and commit" is
// one action whatever the count.
func compare(root string, pages map[string]string) ([]string, error) {
	var diff []string
	for _, rel := range sortedPages(pages) {
		got, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(rel)))
		if os.IsNotExist(err) {
			diff = append(diff, "missing: "+rel)
			continue
		}
		if err != nil {
			return nil, err
		}
		if string(got) != pages[rel] {
			diff = append(diff, "out of date: "+rel)
		}
	}
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			if os.IsNotExist(err) && path == root {
				return nil
			}
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".md") {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		if _, ok := pages[filepath.ToSlash(rel)]; !ok {
			diff = append(diff, "left over: "+filepath.ToSlash(rel))
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(diff)
	return diff, nil
}

func sortedPages(pages map[string]string) []string {
	out := make([]string, 0, len(pages))
	for k := range pages {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
